gensim中必须要知道的概念

在学习任何开源项目都需要先知道这些术语

gensim中的必须理解的概念有：
1 raw strings 原始字符串
2 corpora 语料库
3 sparse vectors 稀疏向量
4 vector space model 向量空间模型
5 transformation 转换，指由稀疏向量组成的稀疏矩阵生成某个向量空间模型。
6 index 索引


## 语料Corpus

一个语料库是数字文档的集合（A Collection of Digital Documents）。 这个集合是gensim的输入，它将从中推断文档的结构或主题。从语料库中推断出的潜在结构（Latent Structure）可用于将主题分配给先前不存在于仅用于训练的语料库中的新文档。

可以说文档的集合称为训练语料库（Training Corpus）。

另外文档不需要标签，因此主题分类是无监督的。

拿到语料库之后需要对语料库进行**分词**，**清洗**与**向量化**，因此有了后面的去停用词，结巴分词，去各种的非文本符号。






## 向量空间

为了推断语料库中的潜在结构（Latent Structure），我们需要一种可用于数学操作（比如，加减乘除等运算）的文档表示方法。一种方法是将每个文档表示为向量。有各种用于创建文档的向量表示的方法，其中一个简单的方法是词袋模型(Bag-of-Words Model)。


在词袋模型下，每个文档由包含字典中每个单词的频率计数的向量表示。向量的长度是字典中的词汇数。词袋模型的一个主要特性是它完全忽略了编码文档（the Encoded Document）中的词汇顺序，这就是词袋模型的由来。


例如，给定一个包含词汇['咖啡'，'牛奶'，'糖果'，'勺子']的字典，那么，一个由字符串'咖啡 牛奶 糖果 勺子'组成的文档可以用向量表示为[2 ，1，0,0]，其中向量的元素（按顺序）对应文档中出现的“咖啡”，“牛奶”，“糖”和“勺子”。

## 模型Model


### tfidf

1. 生成字典 dictionary = corpora.Dictionary(train)
2. 生成语料 corpus = [dictionary.doc2bow(text) for text in train]
3. 定义TFIDF模型 tfidf_model = models.TfidfModel(corpus, dictionary=dictionary)
4. 用语料训练模型并生成TFIDF矩阵 corpus_tfidf = tfidf_model[corpus]
5. 生成余弦相似度索引 index = similarities.SparseMatrixSimilarity(corpus_tfidf, num_features=featurenum) 使用SparseMatrixSimilarity()，可以占用更少的内存和磁盘空间。